index:
    path:     /
    defaults: { _controller: NbGraphicsCoreBundle:Default:index }

order:
    path:   /order
    defaults: { _controller: NbGraphicsCoreBundle:Order:order }

recap:
    path:   /recap
    defaults: { _controller: NbGraphicsCoreBundle:Order:recap }