index:
    path:     /
    defaults: { _controller: NbGraphicsCoreBundle:Default:index }

order:
    path:   /order
    defaults: { _controller: NbGraphicsCoreBundle:Order:order }

recap:
    path:   /recap
    defaults: { _controller: NbGraphicsCoreBundle:Recap:recap }

prepare:
    path:   /prepare
    defaults: { _controller: NbGraphicsCoreBundle:Payment:prepare }

checkout:
    path:   /checkout
    defaults: { _controller: NbGraphicsCoreBundle:Payment:checkout }

confirmation:
    path:   /confirmation
    defaults: { _controller: NbGraphicsCoreBundle:Payment:sendTicket }
