services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
#    nb_graphics_core.example:
#        class: NbGraphics\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    nb_graphics_core.pricing:
        class: NbGraphics\CoreBundle\Services\Pricing

    nb_graphics_core.booking:
        class: NbGraphics\CoreBundle\Services\Booking
        arguments:
            - "@nb_graphics_core.pricing"



