services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: true


    nb_graphics_core.pricing:
        class: NbGraphics\CoreBundle\Services\Pricing
        arguments:
            - "%tarif%"
            - "%age%"

    nb_graphics_core.booking:
        class: NbGraphics\CoreBundle\Services\Booking
        arguments:
            - "@nb_graphics_core.pricing"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
    nb_graphics_core.payment:
        class: NbGraphics\CoreBundle\Services\Payment
        arguments:
            - "@nb_graphics_core.booking"
            - "@doctrine.orm.entity_manager"
            - "@mailer"
            - "@templating"








